# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
AdminUser.create!(email: 'admin@example.com', password: 'password', password_confirmation: 'password') if Rails.env.development?
Actor.create!(name: 'Robert Downey Jr.', bio: 'Robert John Downey Jr. (born April 4, 1965) is an American actor. His career has included critical and popular success in his youth, followed by a period of substance abuse and legal troubles, and a resurgence of commercial success in middle age.', gender: 'male')
Actor.create!(name: 'George Clooney', bio: 'George Timothy Clooney (born May 6, 1961) is an American actor, filmmaker, activist, businessman, and philanthropist. He has received three Golden Globe Awards for his work as an actor and two Academy Awards, one for acting in Syriana (2006) and the other for co-producing Argo.', gender: 'male')
Actor.create!(name: 'Meryl Streep', bio: 'Mary Louise "Meryl" Streep (born June 22, 1949) is an American actress and philanthropist. Cited in the media as the "best actress of her generation,". Nominated for 20 Academy Awards, nd is one of the six actors to have won three or more competitive Oscars for acting. Streep has also received 30 Golden Globe nominations, winning eight.', gender: 'female')
Actor.create!(name: 'Hugh Jackman', bio: 'Hugh Michael Jackman (born 12 October 1968) is an Australian actor, singer, and producer. Jackman has won international recognition for his roles in a variety of film genres. He is known for his long-running role as Wolverine in the X-Men film series. His work in Les Misérables earned him his first Academy Award nomination for Best Actor and his first Golden Globe Award for Best Actor – Motion Picture Musical or Comedy in 2013.', gender: 'male')
Actor.create!(name: 'Mark Ruffalo', bio: 'Mark Alan Ruffalo (born November 22, 1967) is an American actor, filmmaker, and social activist. He made his screen debut in an episode of CBS Summer Playhouse (1989), followed by minor film roles. He was part of the original cast of This Is Our Youth (1996), for which he was nominated for an Independent Spirit Award. ', gender: 'male')
Actor.create!(name: 'Nicole Kidman', bio: 'Nicole Mary Kidman, AC (born 20 June 1967) is an Australian actress, singer, model and film producer. She is the recipient of several awards, including an Academy Award, a BAFTA Award, three Golden Globe Awards, and the Silver Bear for Best Actress.', gender: 'female')
Actor.create!(name: 'Sandra Bullock', bio: 'Sandra Annette Bullock (born July 26, 1964) is an American actress, producer, and philanthropist.Bullock made her acting debut with a minor role in the 1987 thriller Hangmen, and made her television debut in the film Bionic Showdown: The Six Million Dollar Man and the Bionic Woman. She subsequently starred in several successful films including Speed (1994), While You Were Sleeping (1995), The Net (1995), A Time to Kill (1996), Hope Floats (1998), and Practical Magic (1998).', gender: 'female')
Actor.create!(name: 'Leonardo DiCaprio', bio: 'Leonardo Wilhelm DiCaprio (born November 11, 1974) is an American actor, film producer, and environmental activist. DiCaprio began his career by appearing in television commercials in the early 1990s, after which he had recurring roles in various television series. He gained public recognition with leading roles in The Basketball Diaries (1995) and the romantic drama Romeo + Juliet (1996), before achieving international fame with James Camerons epic romance Titanic (1997), which became the highest-grossing film of all time until Camerons science fiction film Avatar (2009) overtook it.', gender: 'male')
Actor.create!(name: 'Julia Roberts', bio: 'Julia Fiona Roberts (born October 28, 1967) is an American actress and producer. She became a Hollywood star after headlining the romantic comedy Pretty Woman (1990), which grossed US $464 million worldwide. She has won three Golden Globe Awards (out of eight nominations) and has been nominated for four Academy Awards for her film acting, winning the Academy Award for Best Actress for her performance in Erin Brockovich (2000).', gender: 'female')
